apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: istio/base
    repoURL: https://istio-release.storage.googleapis.com
    targetRevision: 1.13.2

  destination:
    server: https://kubernetes.default.svc
    destination: istio-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
