---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-sb1-code-change
spec:
  webhook:
    example:
      port: "12000"
      endpoint: /sb1
      method: POST
---
apiVersion: v1
kind: Service
metadata:
  name: github-sb1-code-change
spec:
  ports:
    - port: 12001
      protocol: TCP
      targetPort: 12000
  selector:
    eventsource-name: github-sb1-code-change
  type: NodePort
  externalIPs:
    - 45.118.132.73
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sb1-code-change
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: github-sb1-code-change
      eventName: github-sb1-code-change
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: message
                      # the value will get overridden by event payload from test-dep
                      value: hello world
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value