---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-admin
rules:
  - apiGroups:
      - workflows.argoproj.io
    resources:
      - *
    verbs:
      - create
      - get
      - list
      - update

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow-admin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-admin
subjects:
  - kind: ServiceAccount
    name: argo-workflow-admin
    namespace: argoworkflow