apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgCUiaxE3ll4apEbDAZQKVTFwEEwBQWULuTleE0ISQU4l3cFLspK1jtvD8MWAXYFf7qPRhzahC/iUF6rJEgcPTUZenoEIU0RN1G6ChBmO5ZbzBjgk2LgjgFttbSy5JJt4ocn0guxjPzv38XSQOOXdtiNWXwY+0at5tJKFgcPCl8pfocIAX2DdwSMKKRys3M8Xn10CQWdcNLhGJM38dwPgapKMw4jHkKD4rvNIGDHdxDYY1A7NlAmlBTQCheFyEd/h0xPYbn5qDOxsQYk6gNW1hoWUeRqn0TQQR+z1uc/hIr3GtRBXFKr6LU4ROlwY/PswwHefindjDpDG8+I1etyqMcbfBDWcmRuOgehnzv1h6jOABBFTYqKLdLnPeAEbsHIpcCZOrYYXBcFe5UniFNppR89Lzm1ekfWDCnhyzuUir2WBf/qQ/R3VpLYTI9PI3TCPnMVIbcZ5xdtgWbY4ElOtj7jtMqs5KQxnBNdEh3F7FGvJk3bmjC/Ekk+h3iZ50LDWUqFumkb7Q/UX6BwhYvg4D3Oe75oOveHAEBd0Ljwfz/JBpnF11EaTjb1534AV4z0fzHTxUj70bf56+C1sqLPkMIJuRlLziDxqyBNHTFmcYeucKcdTdNX4O7cdoLuQ8oJyk0jBu8eduNi+Q143ROVYysNV6srTCeU32DLb0KLybRZgJ2v7mRQ80PdcCnChu/4yo7taqw48rv2ujNGdpZXShlvWms0XqOsnWRkNwyJ93Q8eaDGC6uCi/dbFRjUWFCwxzrUgmfr6J2O8PJNp0vQNHIun7vKjWhj/549CiJtz1JEieSyhQQ6JSW59O2h2HFaaC/vKbwW3ISE7jeJDOrouehwqHNBQsIOUdP6BUPu7qWo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo
    type: kubernetes.io/dockerconfigjson

