apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-tools
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster Tools Project
  sourceRepos:
    - '*'
  destinations:
    server: https://kubernetes.default.svc
    namespace: argocd
